package org.common.utility;

public enum ResultMessage {
	SUCCESS, NOT_EXIST, EXIST, WRONG_FORMAT, WRONG_VALUE,WRONG_PASSWORD,WRONG_USERNAME,
	CONNECTION_FAIL, CREDIT_NOT_ENOUGH, ROOM_NOT_ENOUGH, WRONG_ORDER_TYPE
	
}
